// This file will be auto-generated by Supabase CLI
// Run: npm run db:generate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          role_id: number
          full_name: string
          avatar_url: string | null
          phone: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          role_id?: number
          full_name: string
          avatar_url?: string | null
          phone?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role_id?: number
          full_name?: string
          avatar_url?: string | null
          phone?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      roles: {
        Row: {
          id: number
          name: string
          display_name: string
          permissions: Json
          created_at: string
        }
        Insert: {
          id?: number
          name: string
          display_name: string
          permissions?: Json
          created_at?: string
        }
        Update: {
          id?: number
          name?: string
          display_name?: string
          permissions?: Json
          created_at?: string
        }
      }
      products: {
        Row: {
          id: string
          supplier_id: string | null
          category_id: string | null
          sku: string | null
          ref_code: string | null
          name: string
          brand: string | null
          model: string | null
          size: string | null
          unit: string
          reorder_point: number
          standard_cost: number | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          supplier_id?: string | null
          category_id?: string | null
          sku?: string | null
          ref_code?: string | null
          name: string
          brand?: string | null
          model?: string | null
          size?: string | null
          unit?: string
          reorder_point?: number
          standard_cost?: number | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          supplier_id?: string | null
          category_id?: string | null
          sku?: string | null
          ref_code?: string | null
          name?: string
          brand?: string | null
          model?: string | null
          size?: string | null
          unit?: string
          reorder_point?: number
          standard_cost?: number | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      stock_items: {
        Row: {
          id: string
          product_id: string
          lot_number: string
          expiry_date: string | null
          quantity: number
          reserved_quantity: number
          cost_price: number | null
          location: string | null
          received_at: string
          received_by: string | null
          invoice_number: string | null
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          product_id: string
          lot_number: string
          expiry_date?: string | null
          quantity?: number
          reserved_quantity?: number
          cost_price?: number | null
          location?: string | null
          received_at?: string
          received_by?: string | null
          invoice_number?: string | null
          status?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          lot_number?: string
          expiry_date?: string | null
          quantity?: number
          reserved_quantity?: number
          cost_price?: number | null
          location?: string | null
          received_at?: string
          received_by?: string | null
          invoice_number?: string | null
          status?: string
          created_at?: string
          updated_at?: string
        }
      }
      cases: {
        Row: {
          id: string
          case_number: string | null
          patient_id: string
          dentist_id: string
          assistant_id: string | null
          scheduled_date: string
          scheduled_time: string | null
          procedure_type: string | null
          traffic_light: string
          status: string
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          case_number?: string | null
          patient_id: string
          dentist_id: string
          assistant_id?: string | null
          scheduled_date: string
          scheduled_time?: string | null
          procedure_type?: string | null
          traffic_light?: string
          status?: string
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          case_number?: string | null
          patient_id?: string
          dentist_id?: string
          assistant_id?: string | null
          scheduled_date?: string
          scheduled_time?: string | null
          procedure_type?: string | null
          traffic_light?: string
          status?: string
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      reservations: {
        Row: {
          id: string
          case_id: string
          stock_item_id: string
          quantity: number
          status: string
          reserved_by: string
          reserved_at: string
          used_at: string | null
          used_by: string | null
          cancelled_at: string | null
          cancelled_by: string | null
          cancel_reason: string | null
        }
        Insert: {
          id?: string
          case_id: string
          stock_item_id: string
          quantity?: number
          status?: string
          reserved_by: string
          reserved_at?: string
          used_at?: string | null
          used_by?: string | null
          cancelled_at?: string | null
          cancelled_by?: string | null
          cancel_reason?: string | null
        }
        Update: {
          id?: string
          case_id?: string
          stock_item_id?: string
          quantity?: number
          status?: string
          reserved_by?: string
          reserved_at?: string
          used_at?: string | null
          used_by?: string | null
          cancelled_at?: string | null
          cancelled_by?: string | null
          cancel_reason?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      reserve_stock: {
        Args: {
          p_case_id: string
          p_product_id: string
          p_quantity: number
          p_user_id: string
        }
        Returns: string
      }
      use_reserved_stock: {
        Args: {
          p_reservation_id: string
          p_photo_url: string | null
          p_user_id: string | null
        }
        Returns: string
      }
      partial_use_reservation: {
        Args: {
          p_reservation_id: string
          p_quantity_used: number
          p_photo_url: string | null
          p_reason: string | null
          p_user_id: string | null
        }
        Returns: string
      }
      cancel_reservation: {
        Args: {
          p_reservation_id: string
          p_reason: string | null
          p_user_id: string | null
        }
        Returns: boolean
      }
      swap_reservation: {
        Args: {
          p_reservation_id: string
          p_new_stock_item_id: string
          p_reason: string | null
          p_user_id: string | null
        }
        Returns: string
      }
      steal_reservation: {
        Args: {
          p_from_reservation_id: string
          p_to_case_id: string
          p_reason: string | null
          p_user_id: string | null
        }
        Returns: string
      }
      use_unreserved_stock: {
        Args: {
          p_case_id: string
          p_stock_item_id: string
          p_quantity: number
          p_photo_url: string | null
          p_user_id: string | null
        }
        Returns: string
      }
      update_case_traffic_light: {
        Args: {
          p_case_id: string
        }
        Returns: string
      }
      run_daily_maintenance: {
        Args: Record<string, never>
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
